name: Build Mac App
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install pyinstaller pillow pandas

      - name: Build Mac App Bundle
        run: |
          # --windowed se Mac ka folder structure bany ga
          python3 -m PyInstaller --windowed --onefile --name "UltraResizer_Pro" resizer_final.py

      - name: Zip the App Folder
        run: |
          # Mac app aik folder hoti hai, is liye zip karna lazmi hai
          cd dist
          zip -r UltraResizer_Mac.zip UltraResizer_Pro.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS_Final_App
          path: dist/UltraResizer_Mac.zip
