name: Build Mac App
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install pyinstaller pillow pandas

      - name: Build Mac App Bundle
        run: |
          # --windowed se Mac ka asli folder (.app) bany ga
          python3 -m PyInstaller --windowed --onefile --name "UltraResizer_Pro" resizer_final.py

      - name: Create Flashable Zip
        run: |
          # App ko zip karna lazmi hai taaky Windows usay kharab na kary
          cd dist
          zip -r UltraResizer_MacOS_Final.zip UltraResizer_Pro.app

      - name: Upload Artifact
        uses: artifacts/upload-artifact@v4
        with:
          name: MacOS_Final_Package
          path: dist/UltraResizer_MacOS_Final.zip
